# Generated by Django 4.1.7 on 2023-06-16 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('IFSC', models.TextField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('branch_name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('contact', models.IntegerField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('bank_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.banks')),
            ],
        ),
    ]
