# Generated by Django 4.1.7 on 2023-06-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_branches_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banks',
            name='id',
        ),
        migrations.AlterField(
            model_name='banks',
            name='bank_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
